### ISSUE TITLE
第三步文件缺失

### ISSUE THREAD

**Issue by NOKI-RYUU** [Jun-jie-Huang/OTTeR#1]
Step 3: Train the OTTeR
报错信息：

Traceback (most recent call last):
  File "/home/OTTeR/scripts/train_1hop_tb_retrieval.py", line 29, in <module>
    from retrieval.data.tr_dataset import TRDatasetNega, TRDatasetNegaMeta, tb_collate
  File "/home/OTTeR/scripts/../retrieval/data/tr_dataset.py", line 9, in <module>
    from .data_utils import collate_tokens
ModuleNotFoundError: No module named 'retrieval.data.data_utils'

**Comment by Jun-jie-Huang** [comment]
Hi, we have update the module to [https://github.com/Jun-jie-Huang/OTTeR/blob/main/retrieval/data/data_utils.py](https://github.com/Jun-jie-Huang/OTTeR/blob/main/retrieval/data/data_utils.py).

**Comment by NOKI-RYUU** [comment]
> Hi, we have update the module to https://github.com/Jun-jie-Huang/OTTeR/blob/main/retrieval/data/data_utils.py.

It works. Thanks a lot.
